### ISSUE TITLE
Poor namespace naming

### ISSUE THREAD

**Issue by SOF3** [RTGDaCoder/BanCID#3]
The plugin is under the namespace `CID\RTG`, which is bad.

The namespace format `aUniqueNameForTheAuthor\PluginName` is recommended. It is also recommended that your author name be your GitHub username, i.e. `RTGNetworkkk` for you. Violations of these formats may lead to your plugin not being accepted on Poggit Release.

It is also recommended, although not required, that you have reasonably distinctive sub-namespaces for each of your plugins, so that you won't duplicate yourself in the future. For example, for this plugin, `RTGNetworkkk\BanCID` is a good namespace. Your classes can be named under this namespace to minimize the chance of duplication as well as to identify your plugin from your namespace easily.

For this reason, your submission on Poggit Release has been rejected. As we have not fully completed the part about reviewing plugins, I have temporarily set your submission to "Draft", and providing feedback here.

**Comment by RTGDaCoder** [comment]
Ok, noted!
